# Misfits Add - editorHidden to hide all _RMC tiles from spawn menus
- type: tile
  abstract: true
  id: CMTileBase
  editorHidden: true
  baseTurf: CMFloorPlating
  isSubfloor: false
  deconstructTools: [ Prying ]
  footstepSounds:
    collection: FootstepFloor
  itemDrop: CMTileItemSteel
  heatCapacity: 10000
  friction: 1

- type: tile
  abstract: true
  parent: CMTileBase
  id: CMTileBaseUnpryable
  deconstructTools: [ ]
