- type: entity
  abstract: true
  id: RMCPropBase
  categories: [ HideSpawnMenu ]
  placement:
    mode: SnapgridCenter
  components:
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Clickable
  - type: DeleteOnExplosion
